name: Heroku Deployment
on:
  push:
    branches:
      - main
jobs:
    herokudeploy:
      name: Deploy to Heroku
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v2
        - name: Deploy a64a44945-rest-dotnet
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: a64a44945-rest-dotnet
            heroku_email: ${{ secrets.HEROKU_EMAIL }}
            region: eu
            usedocker: true
            appdir: rest_dotnet
            docker_build_args: |
              BACKEND_API_URL
          env:
            BACKEND_API_URL: 'https://a64a44945-rest-dotnet.herokuapp.com'
        - name: Deploy af8eb09a8-frontend-react-with
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: af8eb09a8-frontend-react-with
            heroku_email: ${{ secrets.HEROKU_EMAIL }}
            region: eu
            usedocker: true
            appdir: frontend_react_with_rest
            docker_build_args: |
              BACKEND_API_URL
          env:
            BACKEND_API_URL: 'https://a64a44945-rest-dotnet.herokuapp.com'
